### ISSUE TITLE
Rename path t-streams/src/main/scala-2.11/com/bwsw/tstreams/coordination/subscribe/

### ISSUE THREAD

**Issue by bwsw** [bwsw/t-streams#10]
From t-streams/src/main/scala-2.11/com/bwsw/tstreams/coordination/subscribe/
To t-streams/src/main/scala-2.11/com/bwsw/tstreams/coordination/pubsub/

**Comment by alexander-branevskiy** [comment]
done

**Comment by bwsw** [comment]
resolved
