### ISSUE TITLE
Build conflicts

### ISSUE THREAD

**Issue by alexander-branevskiy** [bwsw/t-streams#13]
all external lib conflicts which need to be resolved (just temporary fixes, in future will be resolved with maven)

**Comment by Wombasta** [comment]
//COMMON
libraryDependencies ++= Seq(
  "org.slf4j" % "slf4j-api" % "1.7.21",
  "org.scalatest" % "scalatest_2.11" % "3.0.0-M15",
  "io.netty" % "netty-all" % "4.1.0.CR7",
  "com.aerospike" % "aerospike-client" % "3.2.1",
  "org.apache.commons" % "commons-collections4" % "4.1",
  "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.6.3",
  "net.openhft" % "chronicle-queue" % "4.2.6",
  "org.scala-lang" % "scala-reflect" % "2.11.8",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.4",
  "log4j" % "log4j" % "1.2.17",
  "org.apache.zookeeper" % "zookeeper" % "3.4.6",
  "org.slf4j" % "slf4j-simple" % "1.7.5" //TODO
)

libraryDependencies += ("com.datastax.cassandra" % "cassandra-driver-core" % "3.0.0")
  .exclude("io.netty", "netty-common")
  .exclude("io.netty", "netty-codec")
  .exclude("io.netty", "netty-transport")
  .exclude("io.netty", "netty-buffer")
  .exclude("io.netty", "netty-handler")

//COORDINATION
resolvers += "twitter resolver" at "http://maven.twttr.com"
libraryDependencies += ("com.twitter.common.zookeeper" % "lock" % "0.0.38")
  .exclude("org.slf4f", "slf4j-api")
  .exclude("log4j","log4j")
  .exclude("io.netty", "netty")
  .exclude("org.slf4j","slf4j-log4j12")
  .exclude("org.apache.zookeeper", "zookeeper")

**Comment by alexander-branevskiy** [comment]
<< resolved
