### ISSUE TITLE
Possible netty optimizations

### ISSUE THREAD

**Issue by alexander-branevskiy** [bwsw/t-streams#20]
1. Try to use netty client instead of raw sockets
2. http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#18.0
3. http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#28.0
4. http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#29.0
5. 
NioEventLoopGroup → EpollEventLoopGroup
NioEventLoop → EpollEventLoop
NioServerSocketChannel → EpollServerSocketChannel
NioSocketChannel → EpollSocketChannel
6. https://www.bountysource.com/issues/1322053-optimize-writeandflush-for-lots-of-small-messages-do-smart-autoflush

**Comment by bwsw** [comment]
decline
