### ISSUE TITLE
"Persistent" ephemeral node in Zookeeper

### ISSUE THREAD

**Issue by alexander-branevskiy** [bwsw/t-streams#45]
There is a case when ZkService is interrupted during runtime. In can cause ephemeral infinite node existence. Need to fix it

Case : 
zk: master=localhost:8888 (infinite corrupted node)

agent with host localhost:8888 perform getMaster action and send message to self. But he is not a master so he respond i am not a master. => infinite loop

**Comment by alexander-branevskiy** [comment]
We can just clean it, but it's not good solution. Need to watch zk logs

**Comment by bwsw** [comment]
Workaround with #56 (probably partial, not all possible cases).
