### ISSUE TITLE
Rework TTS

### ISSUE THREAD

**Issue by bwsw** [bwsw/t-streams#659]
checkpointgroup.roles-permitted=general,closer
checkpointgroup.auth=blabla
checkpointgroup.endpoints=127.0.0.1:2181,192.168.1.1:2181,192.168.1.2:2181
checkpointgroup.roles.general.endpoints=/tts/opener
checkpointgroup.roles.closer.endpoints=/tts/closer
checkpointgroup.streams=/tts/streams

**Comment by ognelis** [comment]
# stream 1

checkpointgroup.roles-permitted=general
checkpointgroup.auth=blabla
checkpointgroup.endpoints=127.0.0.1:2181,192.168.1.1:2181,192.168.1.2:2181
checkpointgroup.roles.general.path=/tts/s1
checkpointgroup.roles.closer.path=/tts/closer
checkpointgroup.streams=/tts/streams


# stream 2

checkpointgroup.roles-permitted=general
checkpointgroup.auth=blabla
checkpointgroup.endpoints=127.0.0.1:2181,192.168.1.1:2181,192.168.1.2:2181
checkpointgroup.roles.general.path=/tts/s2
checkpointgroup.roles.closer.path=/tts/closer
checkpointgroup.streams=/tts/streams


# checkpoint server

checkpointgroup.roles-permitted=closer
checkpointgroup.auth=blabla
checkpointgroup.endpoints=127.0.0.1:2181,192.168.1.1:2181,192.168.1.2:2181
checkpointgroup.roles.closer.path=/tts/closer
