### ISSUE TITLE
Make benchmark to test 'new', 'data' and 'checkpoint' methods.

### ISSUE THREAD

**Issue by Krisilda** [bwsw/t-streams#667]
1. Time each method work. 
2. Check benchmark locally.

**Comment by tomskikh** [comment]
To run benchmark:
`sbt "test:runMain com.bwsw.tstreams.benchmark.ProducerBenchmarkRunner -a <zookeepe-address> -t <token> -p <prefix>"`
e.g
`sbt "test:runMain com.bwsw.tstreams.benchmark.ProducerBenchmarkRunner -a localhost:2181 -t benchmark -p /tts/master"`
