### ISSUE TITLE
Run benchmark to test 'new', 'data' and 'checkpoint' methods  and write results into table 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/t-streams#669]
1. Run benchmark to test 'new', 'data' and 'checkpoint' methods 100 thousand times on vm. 
2. Add results into a table to form future report with data from all benchmarks (create the table here https://drive.google.com/drive/folders/1XQpiG_k8pSd_4vJhcdnu0cgXTIWvCZYz). 
Format of the table: Method, overage time for non-persistent server, overage time for fault-tolerant server

**Comment by tomskikh** [comment]
https://docs.google.com/spreadsheets/d/1mBgpx9dgzW-FXvFtkexAMDa504QMPhMVi_qL0lqkPTI
