### ISSUE TITLE
Implement benchmark to test 'getTxn' method

### ISSUE THREAD

**Issue by Krisilda** [bwsw/t-streams#673]
1. Need to do before calling 'getTxn': 'new', 'data' and 'checkpoint'. 
2. Time 'get Txn' method work.
3. Check benchmark locally.

**Comment by tomskikh** [comment]
To run benchmark:

`sbt "test:runMain com.bwsw.tstreams.benchmark.ConsumerBenchmarkRunner -a <zk-address> -t <auth-token> -p <path-to-master> --load-data"`
