### ISSUE TITLE
Implement benchmark to test 'scanTxn' method

### ISSUE THREAD

**Issue by Krisilda** [bwsw/t-streams#674]
1. Need to do before calling 'scanTxn': 'new', 'data' and 'checkpoint'.
2. Time 'scanTxn' method work.
3. Benchmark should allow specifying parameter how many transactions will be scanned. 
4. Check benchmark locally.

**Comment by tomskikh** [comment]
To run benchmark:

`sbt "test:runMain com.bwsw.tstreams.benchmark.ConsumerBenchmarkRunner -a <zk-address> -t <auth-token> -p <path-to-master> --load-data --interval 10"`
