### ISSUE TITLE
Deploy fault-tolerant tts server 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/t-streams#678]
This server needs Apache BookKeeper.

**Comment by tomskikh** [comment]
[configs.zip](https://github.com/bwsw/t-streams/files/1538366/configs.zip)


`java -Dconfig=multinode.config.properties -cp tstreams-transaction-server-1.5.0-SNAPSHOT.jar com.bwsw.tstreamstransactionserver.CommonCheckpointGroupServerLauncher`
