### ISSUE TITLE
Implement scheduled RocksDB compaction to remove expired transactions

### ISSUE THREAD

**Issue by tomskikh** [bwsw/t-streams#716]
#713

Add the parameter to configure compaction inerval.
Implement unit tests.
Implement integration tests (IT):
* create IT plan;
* implement.

**Comment by Krisilda** [comment]
Unit and integration tests will be implemented in this task.

**Comment by tomskikh** [comment]
Add the parameter to configure compaction inerval.
Implement unit tests.

**Comment by tomskikh** [comment]
Configuration parameter name: ```rocksdb.compaction-interval```

Integration test:
1. Add transactions
2. Wait > compaction interval, but < TTL
3. Check transactions exists
4. Wait until transactions expired
5. Check transactions and corresponding RocksDB entries doesn't exist

**Comment by tomskikh** [comment]
All transactions' metadata stores in a same RocksDB storage. TTL of this storage is ```rocksdb.transaction-expunge-delay-min```.
Each stream corresponds to specific storage that contains transactions' data. TTL of this storage is ```rocksdb.transaction-ttl-append-ms + stream.ttl```.

**Comment by bwsw** [comment]
@placccebo @tomskikh unify "stream.ttl" name to include min/sec, etc, what is related.
