### ISSUE TITLE
Implement reading of tokens from commit log/bookkeeper and invalidating of transactions if token is expired

### ISSUE THREAD

**Issue by tomskikh** [bwsw/t-streams#730]
#711
* Slave stores a local map containing "tokens -> timestamp" pairs and updates it when receives "authentication" or "token update" message
* Slave get a message "token T expired" -> slave removes T from a local collection and invalidates all open transactions related to T
* Slave get another message with some timestamp -> slave removes the detected expired tokens and invalidates the expired transactions

**Comment by bwsw** [comment]
Ticket LGTM

**Comment by tomskikh** [comment]
Need more time to fix some tests.
